language: shell
os: osx
osx_image: xcode11.2
install:
  - pip3 install --upgrade pip
  - pip3 install -r requirements.txt
script:
  - python3 --version
  - pip3 list
  - echo "Saving Key To File"
  - echo "$GOOGLE_APPLICATION_CREDENTIALS" > credentials.key
